import {
  ProductCollection,
  ProductSize,
  ProductStatus,
  ProductVolume,
} from "./enums/product.enum";
import { ProductInput } from "./types/product";

export const productsData: ProductInput[] = [
  // COFFEE
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Americano",
    productPrice: 2500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Classic hot or iced Americano",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611694/1515x2083.crop_63_rfyzv1.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611688/1515x2083.crop_60_xjrnmq.jpg",
    ], // add your Cloudinary URL(s) here
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Classic Ade",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Refreshing mixed fruit ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611535/1515x2083.crop_19_lzo9bw.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Grapefruit Ade",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Tangy grapefruit ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611511/1515x2083.crop_-_2026-01-05T195725.304_rdp4o4.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Lemon Ade",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Zesty lemon ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611513/1515x2083.crop_-_2026-01-05T195726.016_lzomes.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/151_i0bk1z.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Blue Lemon Ade",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Vibrant butterfly pea lemon ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/55_rhr7cc.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611513/1515x2083.crop_-_2026-01-05T195726.018_yo8qa2.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Special Ade",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Premium special fruit ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/151_i0bk1z.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611516/1515x2083.crop_1_deaiiu.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // SMOOTHIE (5 items)
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Mixed Fruit Smoothie",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Classic blended fruit smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611516/1515x2083.crop_3_dnzfmc.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Yogurt Smoothie",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Creamy yogurt smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611517/1515x2083.crop_4_d6mgzi.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Oreo Choco Smoothie",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Oreo and chocolate smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611670/1515x2083.crop_49_d1iegb.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Dark Choco Smoothie",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Rich dark chocolate smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611707/1515x2083.crop_71_g6itzi.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611688/1515x2083.crop_61_s2abmv.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611707/1515x2083.crop_71_g6itzi.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Mango Smoothie",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Tropical mango smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611688/1515x2083.crop_61_s2abmv.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // BEVERAGE (5 items)
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Grain Latte",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Traditional Korean grain powder latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611694/1515x2083.crop_64_dmeqsh.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611528/1515x2083.crop_14_dlyt38.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611517/1515x2083.crop_4_d6mgzi.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Sweet Potato Latte",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Creamy sweet potato latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611714/1515x2083.crop_76_t6xkdg.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Green Tea Latte",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Matcha green tea latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611714/1515x2083.crop_74_iasalp.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611735/1515x2083.crop_87_jvfr7u.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611714/1515x2083.crop_74_iasalp.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Brown Sugar Milk",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Rich brown sugar fresh milk",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611671/1515x2083.crop_50_zde5tf.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611736/1515x2083.crop_88_ww2iqy.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611730/1515x2083.crop_86_h4asqh.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Earl Grey Milk Tea",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Classic Earl Grey milk tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611675/1515x2083.crop_52_yhfwep.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // JUICE (5 items)
  {
    productCollection: ProductCollection.JUICE,
    productName: "Kiwi Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Fresh no-sugar-added kiwi juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611510/1515x2083.crop_-_2026-01-05T195725.303_iugn9y.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Pineapple Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Fresh pineapple juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611510/1515_zeowua.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Healthy Green Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Nutrient-packed green juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611512/1515x2083.crop_-_2026-01-05T195725.309_nmtw4r.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Apple Carrot Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Fresh apple and carrot blend",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611756/1515x2083.crop_100_v5vxa0.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611756/1515x2083.crop_99_dqsicf.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Tomato Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Pure fresh tomato juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611749/1515x2083.crop_98_pzgnhp.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611742/1515x2083.crop_91_zpybhp.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611748/1515x2083.crop_96_bktzkz.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Cafe Latte",
    productPrice: 3000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Smooth cafe latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611695/1515x2083.crop_66_f1o2fv.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611681/1515x2083.crop_58_x18clc.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Cappuccino",
    productPrice: 3000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Classic cappuccino with foam",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611665/1515x2083.crop_44_waqwaj.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Vanilla Latte",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Sweet vanilla latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611681/1515x2083.crop_55_y1idv7.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611669/1515x2083.crop_47_ruixnd.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Hazelnut Latte",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Nutty hazelnut latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611665/1515x2083.crop_44_waqwaj.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611669/1515x2083.crop_46_texamz.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Iced Espresso",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Strong iced espresso",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611675/1515x2083.crop_51_pqthgv.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Einspänner",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Viennese coffee with whipped cream",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611675/1515x2083.crop_52_yhfwep.jpg",
    ],
    productViews: 7,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Biscoff Americano",
    productPrice: 3000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Americano with lotus biscoff flavor",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/13_ozgpc4.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Caramel Macchiato",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Caramel drizzled macchiato",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611659/1515x2083.crop_40_ab6waf.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611665/1515x2083.crop_45_szohjm.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Cafe Mocha",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Rich chocolate mocha",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611660/1515x2083.crop_41_af9bph.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611670/1515x2083.crop_49_d1iegb.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Brown Sugar Cafe Latte",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Sweet brown sugar latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611671/1515x2083.crop_50_zde5tf.jpg",
    ],
    productViews: 6,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Dalgona Latte",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Korean dalgona (honeycomb) topped latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611670/1515x2083.crop_48_dra2iz.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COFFEE,
    productName: "Einspänner Latte",
    productPrice: 4200,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Einspänner style latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611675/1515x2083.crop_52_yhfwep.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // DECAF COFFEE
  {
    productCollection: ProductCollection.DECAF_COFFEE,
    productName: "Decaf Americano",
    productPrice: 2500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Decaffeinated Americano",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611688/1515x2083.crop_60_xjrnmq.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611681/1515x2083.crop_57_bhggza.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.DECAF_COFFEE,
    productName: "Decaf Cafe Latte",
    productPrice: 3000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Decaf latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611681/1515x2083.crop_58_x18clc.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611658/1515x2083.crop_38_ab1cqb.jpg",
    ],
    productViews: 2,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.DECAF_COFFEE,
    productName: "Decaf Vanilla Latte",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Decaf vanilla latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611669/1515x2083.crop_46_texamz.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611652/1515x2083.crop_36_uzq5gs.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.DECAF_COFFEE,
    productName: "Decaf Hazelnut Latte",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Decaf hazelnut latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611651/1515x2083.crop_34_ij9kmg.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611669/1515x2083.crop_46_texamz.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.DECAF_COFFEE,
    productName: "Decaf Cafe Mocha",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Decaf chocolate mocha",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611660/1515x2083.crop_41_af9bph.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611670/1515x2083.crop_49_d1iegb.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.DECAF_COFFEE,
    productName: "Decaf Biscoff Americano",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Decaf biscoff flavored Americano",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611659/1515x2083.crop_39_tdgswm.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // COLD BREW
  {
    productCollection: ProductCollection.COLD_BREW,
    productName: "Cold Brew",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productVolume: ProductVolume.TWO,
    productDesc: "Smooth cold brew coffee",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611675/1515x2083.crop_51_pqthgv.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611680/1515x2083.crop_54_zzvqpb.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COLD_BREW,
    productName: "Cold Brew Latte",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productVolume: ProductVolume.TWO,
    productDesc: "Cold brew with milk",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611665/1515x2083.crop_43_fjnkv6.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611669/1515x2083.crop_46_texamz.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COLD_BREW,
    productName: "Einspänner Cold Brew",
    productPrice: 4200,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productVolume: ProductVolume.TWO,
    productDesc: "Cold brew with cream topping",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611681/1515x2083.crop_56_szefct.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COLD_BREW,
    productName: "Decaf Cold Brew",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productVolume: ProductVolume.TWO,
    productDesc: "Decaf cold brew",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611681/1515x2083.crop_57_bhggza.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611676/1515x2083.crop_53_hgslhd.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.COLD_BREW,
    productName: "Decaf Cold Brew Latte",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productVolume: ProductVolume.TWO,
    productDesc: "Decaf cold brew with milk",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611687/1515x2083.crop_59_chuigx.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611681/1515x2083.crop_58_x18clc.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // TEA & TEA BEVERAGE
  {
    productCollection: ProductCollection.TEA_TEA_BEVERAGE,
    productName: "Herb Tea",
    productPrice: 2500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Relaxing herbal tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611527/1515x2083.crop_13_bnkron.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611757/1515x2083.crop_rlpip3.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.TEA_TEA_BEVERAGE,
    productName: "Black Tea",
    productPrice: 2500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Classic black tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611676/1515x2083.crop_53_hgslhd.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/13_ozgpc4.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.TEA_TEA_BEVERAGE,
    productName: "Fruit Tea",
    productPrice: 3000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Refreshing fruit tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611535/1515x2083.crop_19_lzo9bw.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611511/1515x2083.crop_-_2026-01-05T195725.304_rdp4o4.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.TEA_TEA_BEVERAGE,
    productName: "Ice Tea",
    productPrice: 3000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Iced tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/151_i0bk1z.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611524/1515x2083.crop_11_qiyna4.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.TEA_TEA_BEVERAGE,
    productName: "Ice Tea Mango",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Mango flavored iced tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/2_cx2ddp.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.TEA_TEA_BEVERAGE,
    productName: "Grapefruit Black Tea",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Grapefruit infused black tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611513/1515x2083.crop_-_2026-01-05T195726.017_ckhlyy.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611527/1515x2083.crop_13_bnkron.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // FRAPPE
  {
    productCollection: ProductCollection.FRAPPE,
    productName: "Biscoff Tea Mango Frappe",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Biscoff and mango blended frappe",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611510/654_qrya29.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.FRAPPE,
    productName: "Cookie Choco Frappe",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Cookies and chocolate frappe",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611736/1515x2083.crop_88_ww2iqy.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.FRAPPE,
    productName: "Java Chip Frappe",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Coffee and chocolate chip frappe",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611707/1515x2083.crop_70_kkw7iv.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.FRAPPE,
    productName: "Mint Choco Frappe",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Refreshing mint chocolate frappe",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611721/1515x2083.crop_80_uhm1qu.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.FRAPPE,
    productName: "Green Tea Frappe",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Matcha green tea frappe",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611735/1515x2083.crop_87_jvfr7u.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.FRAPPE,
    productName: "Mocha Java Chip Frappe",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Mocha and java chip blended",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611736/1515x2083.crop_88_ww2iqy.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // COMPOSE MILK SHAKE
  {
    productCollection: ProductCollection.MILKSHAKE,
    productName: "Black Sesame Milk Shake",
    productPrice: 4200,
    productLeftCount: 100,
    productSize: ProductSize.LARGE,
    productVolume: ProductVolume.HALF,
    productDesc: "Rich black sesame milk shake",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611715/1515x2083.crop_77_gy2xyp.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.MILKSHAKE,
    productName: "Candy Milk Shake",
    productPrice: 4200,
    productLeftCount: 100,
    productSize: ProductSize.LARGE,
    productVolume: ProductVolume.HALF,
    productDesc: "Sweet candy flavored milk shake",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611721/1515x2083.crop_80_uhm1qu.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.MILKSHAKE,
    productName: "Coffee Milk Shake",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.LARGE,
    productVolume: ProductVolume.HALF,
    productDesc: "Creamy coffee milk shake",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611723/1515x2083.crop_82_lg8vww.jpg",
    ],
    productViews: 9,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.MILKSHAKE,
    productName: "Cookie Milk Shake",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.LARGE,
    productVolume: ProductVolume.HALF,
    productDesc: "Cookies blended milk shake",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611729/1515x2083.crop_84_fvxiux.jpg",
    ],
    productViews: 2,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.MILKSHAKE,
    productName: "Red Bean Milk Shake",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.LARGE,
    productVolume: ProductVolume.HALF,
    productDesc: "Traditional Korean red bean milk shake",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611743/1515x2083.crop_93_ec9im4.jpg",
    ],
    productViews: 6,
    productStatus: ProductStatus.PROCESS,
  },
];

export const additionalProductsData: ProductInput[] = [
  // ADE (5 items)
  {
    productCollection: ProductCollection.ADE,
    productName: "Classic Ade",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Refreshing mixed fruit ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611535/1515x2083.crop_19_lzo9bw.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Grapefruit Ade",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Tangy grapefruit ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611511/1515x2083.crop_-_2026-01-05T195725.304_rdp4o4.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Lemon Ade",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Zesty lemon ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611513/1515x2083.crop_-_2026-01-05T195726.016_lzomes.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/151_i0bk1z.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Blue Lemon Ade",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Vibrant butterfly pea lemon ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/55_rhr7cc.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611513/1515x2083.crop_-_2026-01-05T195726.018_yo8qa2.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.ADE,
    productName: "Special Ade",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Premium special fruit ade",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611509/151_i0bk1z.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611516/1515x2083.crop_1_deaiiu.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // SMOOTHIE (5 items)
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Mixed Fruit Smoothie",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Classic blended fruit smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611516/1515x2083.crop_3_dnzfmc.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Yogurt Smoothie",
    productPrice: 4000,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Creamy yogurt smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611517/1515x2083.crop_4_d6mgzi.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Oreo Choco Smoothie",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Oreo and chocolate smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611670/1515x2083.crop_49_d1iegb.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Dark Choco Smoothie",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Rich dark chocolate smoothie",
    productImages: [],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.SMOOTHIE,
    productName: "Mango Smoothie",
    productPrice: 4500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Tropical mango smoothie",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611688/1515x2083.crop_61_s2abmv.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // BEVERAGE (5 items)
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Grain Latte",
    productPrice: 3300,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Traditional Korean grain powder latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611694/1515x2083.crop_64_dmeqsh.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611528/1515x2083.crop_14_dlyt38.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611517/1515x2083.crop_4_d6mgzi.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Sweet Potato Latte",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Creamy sweet potato latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611714/1515x2083.crop_76_t6xkdg.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Green Tea Latte",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Matcha green tea latte",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611714/1515x2083.crop_74_iasalp.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611735/1515x2083.crop_87_jvfr7u.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611714/1515x2083.crop_74_iasalp.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Brown Sugar Milk",
    productPrice: 3500,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Rich brown sugar fresh milk",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611671/1515x2083.crop_50_zde5tf.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611736/1515x2083.crop_88_ww2iqy.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611730/1515x2083.crop_86_h4asqh.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.BEVERAGE,
    productName: "Earl Grey Milk Tea",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Classic Earl Grey milk tea",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611675/1515x2083.crop_52_yhfwep.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },

  // JUICE (5 items)
  {
    productCollection: ProductCollection.JUICE,
    productName: "Kiwi Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Fresh no-sugar-added kiwi juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611510/1515x2083.crop_-_2026-01-05T195725.303_iugn9y.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Pineapple Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Fresh pineapple juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611510/1515_zeowua.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Healthy Green Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Nutrient-packed green juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611512/1515x2083.crop_-_2026-01-05T195725.309_nmtw4r.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Apple Carrot Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Fresh apple and carrot blend",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611756/1515x2083.crop_100_v5vxa0.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611756/1515x2083.crop_99_dqsicf.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
  {
    productCollection: ProductCollection.JUICE,
    productName: "Tomato Juice",
    productPrice: 3800,
    productLeftCount: 100,
    productSize: ProductSize.NORMAL,
    productDesc: "Pure fresh tomato juice",
    productImages: [
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611749/1515x2083.crop_98_pzgnhp.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611742/1515x2083.crop_91_zpybhp.jpg",
      "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611748/1515x2083.crop_96_bktzkz.jpg",
    ],
    productViews: 0,
    productStatus: ProductStatus.PROCESS,
  },
];

// export const frappeData = [
//   // Additional 5 FRAPPE products
//   {
//     productCollection: ProductCollection.FRAPPE,
//     productName: "Biscoff Caramel Frappe",
//     productPrice: 4200,
//     productLeftCount: 100,
//     productSize: ProductSize.NORMAL,
//     productDesc: "Lotus Biscoff cookie blended with caramel frappe",
//     productImages: [
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611670/1515x2083.crop_49_d1iegb.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611660/1515x2083.crop_41_af9bph.jpg",
//     ],
//     productViews: 0,
//     productStatus: ProductStatus.PROCESS,
//   },
//   {
//     productCollection: ProductCollection.FRAPPE,
//     productName: "Strawberry Cream Frappe",
//     productPrice: 4300,
//     productLeftCount: 100,
//     productSize: ProductSize.NORMAL,
//     productDesc: "Fresh strawberry and whipped cream blended frappe",
//     productImages: [
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611714/1515x2083.crop_76_t6xkdg.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611742/1515x2083.crop_91_zpybhp.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611694/1515x2083.crop_64_dmeqsh.jpg",
//     ],
//     productViews: 0,
//     productStatus: ProductStatus.PROCESS,
//   },
//   {
//     productCollection: ProductCollection.FRAPPE,
//     productName: "Tiramisu Frappe",
//     productPrice: 4500,
//     productLeftCount: 100,
//     productSize: ProductSize.NORMAL,
//     productDesc: "Coffee and mascarpone-inspired tiramisu frappe",
//     productImages: [
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611729/1515x2083.crop_85_n4mv3a.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611738/1515x2083.crop_89_vgbszl.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611721/1515x2083.crop_79_xfejlp.jpg",
//     ],
//     productViews: 0,
//     productStatus: ProductStatus.PROCESS,
//   },
//   {
//     productCollection: ProductCollection.FRAPPE,
//     productName: "Injeolmi Frappe",
//     productPrice: 4300,
//     productLeftCount: 100,
//     productSize: ProductSize.NORMAL,
//     productDesc:
//       "Korean roasted soybean powder (injeolmi) frappe with chewy bits",
//     productImages: [
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611720/1515x2083.crop_78_svi78g.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611709/1515x2083.crop_73_rk9uy2.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611707/1515x2083.crop_71_g6itzi.jpg",
//     ],
//     productViews: 0,
//     productStatus: ProductStatus.PROCESS,
//   },
//   {
//     productCollection: ProductCollection.FRAPPE,
//     productName: "Chocolate Banana Frappe",
//     productPrice: 4300,
//     productLeftCount: 100,
//     productSize: ProductSize.NORMAL,
//     productDesc: "Rich chocolate and real banana blended frappe",
//     productImages: [
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611749/1515x2083.crop_97_auozlh.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611720/1515x2083.crop_78_svi78g.jpg",
//       "https://res.cloudinary.com/dmenptrzv/image/upload/v1767611701/1515x2083.crop_68_trh3lt.jpg",
//     ],
//     productViews: 0,
//     productStatus: ProductStatus.PROCESS,
//   },
// ];
